apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: j-ing
  namespace: jenkins
spec:
  rules:
  - host: gvdganesh.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: j-svc
            port: 
              number: 8080
